import Head from "next/head";
import Message from "../components/message";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import { useEffect, useState } from "react";
import { db } from "../utils/firebase";
import Link from "next/link";

export default function Home() {
  const [allPost, setAllPost] = useState([]);

  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const unsunscribe = onSnapshot(q, (snapshot) => {
      setAllPost(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unsunscribe;
  };



  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-12 text-lg">
        <h2 className="font-medium">See what other people are thinking</h2>
        {allPost.map((post) => {
          return(
          <Message key={post.id} {...post}>
            <Link href={{pathname:`/${post.id}`, query:{...post}}}>
              <button>{post.comments?.length > 0 ? post.comments?.length : "0"} comments</button>
            </Link>
          </Message>
          
        )})}
      </div>
    </div>
  );
}
