import Head from "next/head";
import Message from "../components/message";
import { collection, deleteDoc, doc, onSnapshot, orderBy, query } from "firebase/firestore";
import { useEffect, useState } from "react";
import { db } from "../utils/firebase";
import {BsFillTrashFill} from 'react-icons/bs'
import {AiFillEdit} from 'react-icons/ai'

export default function Home() {
  const [allPost, setAllPost] = useState([]);

  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const unsunscribe = onSnapshot(q, (snapshot) => {
      setAllPost(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unsunscribe;
  };



  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-12 text-lg">
        <h2 className="font-medium">See what other people are thinking</h2>
        {allPost.map((post) => {
          return(<>
          <Message key={post.id} {...post}>
          {/* <div className="flex gap-4">
          <button className="text-pink-600 flex items-center justify-center gap-2 py-2 text-sm">
          <BsFillTrashFill className='text-2xl'/>
          Delete</button>
          <button className=" flex items-center justify-center gap-2 py-2 text-sm">
          <AiFillEdit className='text-2xl' />
          Edit</button>
          </div> */}
          </Message>
          </>
        )})}
      </div>
    </div>
  );
}
